# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LCalendar' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for LCalendar
#  pod 'Masonry'
  pod 'LCalendar', :path => '../'

  target 'LCalendarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LCalendarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
